server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_meter
spring.datasource.username=postgres
spring.datasource.password=Freeze10$
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=pulsemeter-smart-grid-analytics-jwt-secret-key-2026-very-secure-256-bits-long
jwt.expiration=86400000
